using System.Linq;
namespace MfgEnabler;
internal static class CoreText
{
    // Longest match first preserves complete diagnostic sentences before replacing fragments.
    private static readonly (string Ko, string En)[] Messages = {
        ("NVIDIA App 검색 결과가 없습니다. NVIDIA App에서 게임을 검색한 뒤 목록을 새로고침하세요.", "No NVIDIA App scan results. Scan for games in NVIDIA App, then refresh this list."),
        ("NVIDIA App이 검색 결과를 갱신 중이거나 JSON 형식이 올바르지 않습니다. 잠시 후 새로고침하세요.", "NVIDIA App is updating its results or the JSON is invalid. Refresh again shortly."),
        ("지원하지 않는 NVIDIA ApplicationStorage 형식입니다. 기존 스토어 탐색으로 대체하지 않습니다.", "Unsupported NVIDIA ApplicationStorage format."),
        ("NVIDIA App에서 FG 구성을 확인한 게임만 새로 활성화할 수 있습니다.", "Only games with an NVIDIA-detected FG configuration can be enabled."),
        ("NVIDIA 검색 결과 또는 게임 파일이 변경되었습니다. 목록을 새로고침하세요.", "NVIDIA results or game files have changed. Refresh the list."),
        ("현재 NVIDIA FG 후보에 없음 · 기존 적용 해제만 가능합니다.", "No longer an NVIDIA FG candidate. Existing changes can only be restored."),
        ("게임 폴더에 x64 nvngx_dlssg.dll 없음 (SR만으로는 FG 판정 불가)", "No x64 nvngx_dlssg.dll in game folder (SR alone does not establish FG support)"),
        ("NVIDIA fingerprint 확인 · FG 차단 없음", "NVIDIA fingerprint verified · FG not blocked"),
        ("NVIDIA fingerprint 미확인 (수동 등록만 된 항목 포함)", "NVIDIA fingerprint not verified (including manually registered entries)"),
        ("fingerprint.db 없음: NVIDIA 검색 결과에 기록된 실행 경로만 사용합니다.", "No fingerprint.db: using executable paths recorded in NVIDIA results only."),
        ("fingerprint.db 읽기 실패: 검색 결과의 명시적 정보만 사용합니다. ", "Cannot read fingerprint.db: using explicit scan data only. "),
        (" 파일이 이미 있습니다. 다른 프록시를 선택하세요. 기존 모드는 덮어쓰지 않습니다.", " already exists. Choose a different proxy. Existing mods will not be overwritten."),
        ("이 설치 후 변경되었습니다. 파일을 다른 폴더에 보관한 뒤 다시 해제하세요.", " was modified after installation. Move it to a safe folder before restoring."),
        ("새 dlssg_for_sm86 버전 형식을 인식하지 못했습니다. 현재 버전을 유지합니다.", "Unknown dlssg_for_sm86 version format. Keeping the current version."),
        ("dlssg_for_sm86/PTX 기본 설정이 변경되었습니다. 자동 적용을 중단합니다.", "dlssg_for_sm86/PTX defaults have changed. Automatic application stopped."),
        ("게임 또는 해당 폴더의 프로그램을 종료하세요: ", "Close the game or program in this folder: "),
        ("심볼릭 링크/정션 경로는 지원하지 않습니다: ", "Symbolic links and junction paths are not supported: "),
        ("게임 설치 폴더로 볼 수 없는 드라이브 루트", "Drive root is not a game installation folder"),
        ("게임 실행 파일이 없습니다.", "Game executable not found."),
        ("게임 설치 폴더가 유효하지 않습니다.", "Game installation folder is invalid."),
        ("선택한 실행 파일을 찾을 수 없습니다.", "Selected executable not found."),
        ("게임 폴더 안의 x64 실행 파일을 선택하세요.", "Choose an x64 executable inside the game folder."),
        ("게임 외 크리에이티브 앱", "Creative application, not a game"),
        ("다운로드 무결성 확인 실패: ", "Download integrity check failed: "),
        ("먼저 기존 적용을 해제하거나 복구하세요.", "Restore the existing installation first."),
        ("먼저 중단된 작업을 복구하세요.", "Recover the interrupted operation first."),
        ("먼저 해당 기능을 해제하거나 복구하세요.", "Disable or restore this feature first."),
        ("복구 경로에 폴더가 있습니다: ", "A directory exists at the recovery file path: "),
        ("복구 기록이 유효하지 않습니다.", "Invalid recovery journal."),
        ("복구 파일 목록이 유효하지 않습니다.", "Invalid recovery file list."),
        ("복구 중 파일 변경 감지", "File change detected during recovery"),
        ("복구 검증 실패", "Recovery verification failed"),
        ("백업 검증 실패", "Backup verification failed"),
        ("버전 안내 파일 무결성 오류", "Version metadata integrity error"),
        ("불완전한 NVIDIA 검색 항목", "Incomplete NVIDIA scan entry"),
        ("설치 경로 없음 / 제거된 게임", "Missing installation path / uninstalled game"),
        ("설치 중 원본 변경 감지", "Original file changed during installation"),
        ("설치 파일 검증 실패: ", "Installation file verification failed: "),
        ("설치 파일 변경 감지: ", "Installation file changed: "),
        ("설치 후 검증 실패", "Post-installation verification failed"),
        ("수동 설치된 DLSSG 프록시가 있습니다: ", "Manually installed DLSSG proxy found: "),
        (". 먼저 수동 설치를 정리하세요.", ". Remove the manual installation first."),
        ("알 수 없는 복구 상태", "Unknown recovery state"),
        ("알 수 없는 업데이트 파일: ", "Unknown update file: "),
        ("업데이트 도중 파일 변경 감지", "File changed during update"),
        ("업데이트 백업 손상", "Update backup is damaged"),
        ("업데이트 복구 중 외부 변경 감지", "External file change detected during update recovery"),
        ("업데이트 설치 형식이 달라졌습니다: ", "Update installation format has changed: "),
        ("업데이트 직전 파일 변경 감지", "File change detected before update"),
        ("업데이트 캐시 검증 실패", "Update cache verification failed"),
        ("업데이트 파일 목록 또는 해시가 잘못되었습니다.", "Invalid update file list or hash."),
        ("업데이트 파일 크기 제한 초과", "Update file size limit exceeded"),
        ("업데이트 패키지 기록이 유효하지 않습니다.", "Invalid update package record."),
        ("업데이트 없음", "No updates"),
        ("업데이트 확인 실패 · 기존 버전 유지: ", "Update check failed · Keeping current version: "),
        ("업데이트 후 검증 실패", "Post-update verification failed"),
        ("원본 백업 손상: ", "Original backup is damaged: "),
        ("이름 없는 항목", "Unnamed entry"),
        ("이전 버전으로 자동 변경하지 않습니다.", "Automatic downgrades are disabled."),
        ("이전 적용 · 복구 전용", "Previously applied · Recovery only"),
        ("잘못된 백업 경로", "Invalid backup path"),
        ("잘못된 설치 종류", "Invalid installation type"),
        ("잘못된 업데이트 복구 기록", "Invalid update recovery record"),
        ("잘못된 패키지 커밋", "Invalid package commit"),
        ("적용된 MFG만 업데이트할 수 있습니다.", "Only installed MFG can be updated."),
        ("지원하지 않는 프록시", "Unsupported proxy"),
        ("파일 경로에 폴더가 있습니다: ", "A directory exists at the file path: "),
        ("FG 파일 확인 불완전: 접근 불가 또는 탐색 한도", "FG file check incomplete: access denied or search limit reached"),
        ("GitHub 응답 형식 오류", "Invalid GitHub response format"),
        ("GitHub 커밋 정보 오류", "Invalid GitHub commit data"),
        ("GitHub 파일 목록 오류", "Invalid GitHub file list"),
        ("GitHub 파일 목록이 불완전합니다.", "Incomplete GitHub file list."),
        ("GitHub 파일 해시 불일치: ", "GitHub file hash mismatch: "),
        ("NVIDIA 검색 데이터가 너무 큽니다.", "NVIDIA scan data is too large."),
        ("NVIDIA 기록에 유효한 x64 실행 파일 없음", "No valid x64 executable in NVIDIA records"),
        ("NVIDIA App · FG DLL 확인", "NVIDIA App · FG DLL verified"),
        ("NVIDIA App 감지 ", "NVIDIA App detected "),
        ("NVIDIA FG 프로필 정보 없음", "No NVIDIA FG profile data"),
        ("NVIDIA FG override 차단 프로필", "NVIDIA FG override blocked by profile"),
        ("RTX 5080 설치는 EnableSpoof를 사용하세요.", "Use EnableSpoof for RTX 5080 installation."),
        ("RTX 5080 프록시 리소스가 없습니다.", "RTX 5080 proxy resource is missing."),
        ("dlssg_for_sm86 버전 안내 파일이 없습니다.", "dlssg_for_sm86 version metadata is missing."),
        ("dlssg_for_sm86 업데이트 대상이 아닙니다.", "Not eligible for dlssg_for_sm86 updates."),
        ("dlssg_for_sm86 최신 버전 확인 중…", "Checking the latest dlssg_for_sm86 version…"),
        ("v310.9.1 최신 버전 확인 중…", "Checking the latest v310.9.1 version…"),
        ("x64 DLL 형식이 아닙니다: ", "Not an x64 DLL: "),
        (" · 적용 보류: ", " · Deferred: "), (" 다운로드 중…", " downloading…"), (" 적용 중…", " applying…"),
        (": 중복 실행 경로", ": duplicate executable path"), ("개 · 제외 ", " · Excluded "), ("개 · FG 구성 확인 ", " · FG verified "),
        ("개 갱신", " updated"), ("개 보류", " deferred"),
        ("기록 확인 필요", "Check recovery records"), ("미적용", "Off"), ("복구 필요", "Recovery required"),
        ("적용됨", "Applied"), ("파일 변경 감지", "File changes detected"), ("확인 실패", "Check failed"), ("확인 완료", "Check complete"),
        ("FG 구성 파일: ", "FG configuration file: ")
    };
    public static string English(string text)
    {
        foreach (var pair in Messages.OrderByDescending(x => x.Ko.Length)) text = text.Replace(pair.Ko, pair.En);
        return System.Text.RegularExpressions.Regex.Replace(text, @"(?<=\d)개(?=\s|$)", "");
    }
}


